version: '3.5'

services:
  mysql:
    image: mysql:5.6
    networks:
      - traefik
    env_file:
      - ./.env.mysql
    volumes:
      - ./../shared/latest-schema.sql:/docker-entrypoint-initdb.d/latest-schema.sql
      - $HOME/symmetricds/store/mysql/datadir:/var/lib/mysql

networks:
  traefik:
    driver: bridge
    name: traefik
