version: '3.5'

services:
  mysql:
    image: mysql:5.6
    networks:
      - traefik
    env_file:
      - ./.env.mysql
    #volumes:
    #  - config/latest-schema.sql:/docker-entrypoint-initdb.d/latest-schema.sql

networks:
  traefik:
    driver: bridge
    name: traefik
